### PR TITLE
Add compatibility with PHP 8

### PR DESCRIPTION
**Pull request by ausi**
We don’t seem to have a CI toolchain running for this repo, how can we test if this is actually compatible with PHP 8?

### CODE REVIEW

**Comment by m-vo** [comment]
Do I see this correctly? 

In order to test this in this bundle we would really need to bump the PHPUnit version to [9](https://phpunit.de/supported-versions.html) (+ adjust the tests) and add a CI job. And we should be aware that there are quite some things that aren't covered.

**Comment by ausi** [comment]
PHPUnit 8 should now be compatible with PHP 8 https://github.com/sebastianbergmann/phpunit/commit/73435f4bac40a63d18f04707858c738a64c1f7ed

**Comment by m-vo** [comment]
> PHPUnit 8 should now be compatible with PHP 8 sebastianbergmann/phpunit@73435f4

The code still uses an even older version. I made some adjustments in a [new PR](#2).

**Comment by ausi** [comment]
Closed in favor of #2

**Pull request closed without merging**
