### PR TITLE
Add compatibility with PHPUnit 8.5

### PR DESCRIPTION
**Pull request by m-vo**
This PR applies some changes to the tests so that they can run with `phpunit 8.5` / `PHP 8`.

(supersedes #1)

### CODE REVIEW

**Comment by m-vo** [comment]
@leofeyer Not sure if we want to enable a CI for this repository. I added a template in the last commit, but would probably vote for dropping it again.

**Comment by ausi** [comment]
This bundle is deprecated, If the tests run with php 8 I think we don’t need a CI.

**Comment by m-vo** [comment]
> This bundle is deprecated, If the tests run with php 8 I think we don’t need a CI.

Reverted in e9a59dd2510b3c1febef186d4f2f088c70a805eb.

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.

**Pull request merged**
